const preloader=document.querySelector('.preloader');const pageShell=document.querySelector('.page-shell');
window.addEventListener('load',()=>{if(pageShell)pageShell.classList.add('is-ready');if(preloader){preloader.classList.add('is-hidden');setTimeout(()=>preloader.remove(),600)}});
const stack=document.querySelector('.role-stack');if(stack)setInterval(()=>stack.classList.toggle('is-swapped'),2500);
const navToggle=document.getElementById('nav-toggle'),navLinks=document.querySelector('.nav-links');if(navToggle&&navLinks){navToggle.addEventListener('click',()=>{navToggle.classList.toggle('is-open');navLinks.classList.toggle('is-open')});navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navToggle.classList.remove('is-open');navLinks.classList.remove('is-open')}));}
const revealItems=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');obs.unobserve(e.target)}}),{threshold:.12});revealItems.forEach(e=>obs.observe(e))}else revealItems.forEach(e=>e.classList.add('is-visible'));
const tabs=document.querySelectorAll('.xp-tab'),panels=document.querySelectorAll('.xp-panel');tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');panels.forEach(p=>p.classList.toggle('xp-panel--hidden',p.id!==`tab-${tab.dataset.tab}`))}));
const dot=document.querySelector('.cursor-dot');if(dot){let x=0,y=0,cx=0,cy=0;window.addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;document.body.classList.add('cursor-ready')});(function tick(){cx+=(x-cx)*.16;cy+=(y-cy)*.16;dot.style.transform=`translate(${cx}px,${cy}px)`;requestAnimationFrame(tick)})()}
const form=document.querySelector('.contact-form');if(form)form.addEventListener('submit',e=>{e.preventDefault();const name=form.querySelector('[name=name]').value.trim(),email=form.querySelector('[name=email]').value.trim(),message=form.querySelector('[name=message]').value.trim();const subject=encodeURIComponent('Portfolio contact from '+name);const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`);window.location.href=`mailto:Farmankorejo10@gmail.com?subject=${subject}&body=${body}`});

// Portfolio AI assistant
window.addEventListener('DOMContentLoaded',()=>{
  if(document.getElementById('ai-agent-toggle'))return;
  const style=document.createElement('style');style.textContent=`#ai-agent-toggle{position:fixed;right:24px;bottom:24px;z-index:1500;width:58px;height:58px;border:1px solid #9f6bff66;border-radius:50%;background:linear-gradient(135deg,#a35dff,#8547e9);color:#fff;font-size:24px;cursor:pointer;box-shadow:0 12px 35px #6f35b855}#ai-agent-box{position:fixed;right:24px;bottom:94px;z-index:1500;width:340px;max-width:calc(100vw - 30px);height:450px;background:#100b1d;border:1px solid #493265;border-radius:18px;box-shadow:0 25px 80px #000b;display:flex;flex-direction:column;overflow:hidden;opacity:0;transform:translateY(15px) scale(.97);pointer-events:none;transition:.25s}#ai-agent-box.ai-open{opacity:1;transform:none;pointer-events:auto}.ai-head{padding:17px 18px;background:linear-gradient(135deg,#1d1230,#120c20);border-bottom:1px solid #30244a;display:flex;justify-content:space-between;align-items:center}.ai-head strong{font-size:14px}.ai-head small{display:block;color:#9b93aa;font-size:9px;margin-top:2px}.ai-close{border:0;background:transparent;color:#aaa2b8;font-size:20px;cursor:pointer}.ai-msgs{flex:1;padding:16px;overflow:auto;display:flex;flex-direction:column;gap:10px}.ai-msg{max-width:85%;padding:10px 12px;border-radius:12px;font-size:11px;line-height:1.55}.ai-msg.bot{align-self:flex-start;background:#1d1430;color:#d9d0e5;border:1px solid #30244a}.ai-msg.user{align-self:flex-end;background:#8547e9;color:#fff}.ai-input-row{display:flex;gap:8px;padding:12px;border-top:1px solid #30244a}.ai-input{min-width:0;flex:1;background:#0b0817;border:1px solid #30244a;border-radius:10px;color:#fff;padding:10px;font-size:11px;outline:none}.ai-send{border:0;border-radius:10px;background:#a05cff;color:#fff;padding:0 14px;font-weight:700;cursor:pointer}.ai-welcome{padding:12px 14px;border-radius:12px;background:#171027;color:#cfc5dc;font-size:11px;line-height:1.55;border:1px solid #30244a}@media(max-width:560px){#ai-agent-toggle{right:16px;bottom:16px}#ai-agent-box{right:15px;bottom:84px;height:420px}}`;document.head.appendChild(style);
  document.body.insertAdjacentHTML('beforeend',`<button id="ai-agent-toggle" aria-label="Open portfolio AI assistant">✦</button><section id="ai-agent-box" aria-label="Farman AI assistant"><div class="ai-head"><div><strong>Farman AI Assistant</strong><small>Ask about skills, projects &amp; experience</small></div><button class="ai-close" id="ai-agent-close" aria-label="Close">×</button></div><div class="ai-msgs" id="ai-agent-messages"><div class="ai-welcome">Hi! 👋 I’m Farman’s portfolio assistant. Ask me about skills, projects, Java, JDBC, MySQL, GitHub, or contact details.</div></div><div class="ai-input-row"><input id="ai-agent-input" class="ai-input" placeholder="Ask something..." autocomplete="off"><button id="ai-agent-send" class="ai-send">Send</button></div></section>`);
  const toggle=document.getElementById('ai-agent-toggle'),box=document.getElementById('ai-agent-box'),close=document.getElementById('ai-agent-close'),input=document.getElementById('ai-agent-input'),send=document.getElementById('ai-agent-send'),messages=document.getElementById('ai-agent-messages');
  const reply=q=>{q=q.toLowerCase();if(q.includes('skill'))return'Farman works with Java, C++, OOP, MySQL, JDBC, Java Swing, Git/GitHub, HTML and CSS.';if(q.includes('project'))return'Farman has built a Java Swing Game Menu, Student Management System, and Calculator. You can view them in the Projects section.';if(q.includes('java'))return'Java is one of Farman’s main programming skills, including OOP, Swing and desktop application development.';if(q.includes('mysql')||q.includes('jdbc'))return'Farman works with MySQL and JDBC for database-connected Java applications.';if(q.includes('github'))return'You can find Farman’s projects on GitHub from the Projects section or Contact section.';if(q.includes('contact')||q.includes('email'))return'You can contact Farman at Farmankorejo10@gmail.com.';if(q.includes('who')||q.includes('about')||q.includes('farman'))return'Farman Ali Korejo is a Computer Systems Engineering student at MUET who enjoys building practical software projects.';return'I can tell you about Farman’s skills, projects, Java, JDBC, MySQL, GitHub, or contact information.'};
  const add=(text,who)=>{const d=document.createElement('div');d.className='ai-msg '+who;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight};const ask=()=>{const q=input.value.trim();if(!q)return;add(q,'user');input.value='';setTimeout(()=>add(reply(q),'bot'),250)};toggle.onclick=()=>box.classList.toggle('ai-open');close.onclick=()=>box.classList.remove('ai-open');send.onclick=ask;input.addEventListener('keydown',e=>{if(e.key==='Enter')ask()});
});